name: shoe_shopping_app
description: "GDSC Task Round App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  gap: ^3.0.1
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/collection/
    - assets/logo/
    - assets/heroBG.png
    
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/heroBG.png"
